num1 = int(input("enter your number 1: "))
num2 = int(input("enter your number 2: "))
num3 = int(input("enter your number 3: "))
print(num1 + num2 + num3)
print(num1 - num2 - num3)
print(num1 * num2 * num3)
print(num1 / num2 / num3)